### ISSUE TITLE
Can't load Carrefour on Pharo 10 - 11

### ISSUE THREAD

**Issue by alesshosry** [badetitou/Carrefour#7]
I am using Pharo on Mac machine.
I created new Pharo 10 and 11 images but Carrefour couldn't be loaded successfully.
Screenshot is attached 

<img width="1430" alt="Screenshot 2022-11-21 at 4 22 54 PM" src="https://user-images.githubusercontent.com/26387399/203093146-9c09a614-249d-4c7b-aa6b-0eb8dca87781.png">

**Comment by badetitou** [comment]
Did you try with a Moose10 image (Carrefour is made to work with a pre built Moose9/Moose10 image)

**Comment by alesshosry** [comment]
Ok I tried it on Moose 10 image and it works.
Thanks for the clarification
